const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const { parseTripData } = require("../lib/trip-data");

const routes = JSON.parse(fs.readFileSync(path.join(__dirname, "..", "assets", "roadbook-routes.geojson"), "utf8"));
const gpx = fs.readFileSync(path.join(__dirname, "..", "reiseplanung-verfeinert-2026.gpx"), "utf8");
const kml = fs.readFileSync(path.join(__dirname, "..", "reiseplanung-verfeinert-2026-export.kml"), "utf8");
const tripData = parseTripData(fs.readFileSync(path.join(__dirname, "..", "data", "trip-spanien-2026.js"), "utf8"));
const originals = routes.features.filter((feature) => feature.properties.variant === "original");
const direct = routes.features.filter((feature) => feature.properties.variant === "direct");
const roadOriginals = originals.filter((feature) => !feature.properties.ferry);
const publishedRoutes = originals.filter((feature) => !feature.properties.optional);
const day12 = originals.find((feature) => feature.properties.day === 12);
const day15 = originals.find((feature) => feature.properties.day === 15);
const day26 = originals.find((feature) => feature.properties.day === 26);
const distanceKilometers = (a, b) => {
  const radians = Math.PI / 180;
  const latitudeA = a[1] * radians;
  const latitudeB = b[1] * radians;
  const latitudeDelta = (b[1] - a[1]) * radians;
  const longitudeDelta = (b[0] - a[0]) * radians;
  const value = Math.sin(latitudeDelta / 2) ** 2 + Math.cos(latitudeA) * Math.cos(latitudeB) * Math.sin(longitudeDelta / 2) ** 2;
  return 12742 * Math.asin(Math.sqrt(value));
};

assert.equal(routes.type, "FeatureCollection");
assert.equal(routes.features.length, 48);
assert.equal(originals.length, 24);
assert.equal(direct.length, 24);
assert.deepEqual(publishedRoutes.map((feature) => feature.properties.day), tripData.publishedDays.filter((day) => !day.rest).map((day) => day.day));
assert.ok(roadOriginals.every((feature) => feature.geometry.type === "LineString"));
assert.ok(roadOriginals.every((feature) => feature.geometry.coordinates.length >= 20));
assert.ok(roadOriginals.every((feature) => feature.properties.source.startsWith("osrm-driving")));
assert.ok(originals.find((feature) => feature.properties.day === 1).geometry.coordinates.length > 100);
assert.equal(day12.properties.name, "12 Albarracin - La Patacona");
assert.ok(distanceKilometers(day12.geometry.coordinates.at(-1), [-0.3525, 39.4953]) < 1);
assert.equal(day15.properties.name, "15 Altea - Monachil");
assert.ok(distanceKilometers(day15.geometry.coordinates.at(-1), [-3.5398, 37.1322]) < 1);
assert.ok(Math.min(...day15.geometry.coordinates.map((coordinate) => distanceKilometers(coordinate, [-1.1307, 37.9922]))) > 2);
assert.equal(day26.properties.name, "26 Zaragoza - Castelldefels");
assert.ok(Math.abs(day26.geometry.coordinates.at(-1)[0] - 1.9794) < 0.01);
assert.ok(Math.abs(day26.geometry.coordinates.at(-1)[1] - 41.2787) < 0.01);
assert.equal((gpx.match(/<trk>/g) || []).length, 23);
assert.deepEqual(Array.from(gpx.matchAll(/<trk><name>(.*?)<\/name>/g), (match) => match[1]), publishedRoutes.map((feature) => feature.properties.name));
assert.ok(gpx.includes("26 Zaragoza - Castelldefels"));
assert.ok(!gpx.includes("Gorges de la Meouge optional"));
assert.equal((kml.match(/<Placemark>/g) || []).length, 23);
assert.deepEqual(Array.from(kml.matchAll(/<Placemark><name>(.*?)<\/name>/g), (match) => match[1]), publishedRoutes.map((feature) => feature.properties.name));
assert.ok(kml.includes("26 Zaragoza - Castelldefels"));
assert.ok(!kml.includes("Gorges de la Meouge optional"));

console.log("route geometry tests passed");
